import Button, { ButtonType } from './components/atoms/Button';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        ></link>
      </head>
      <body className="container">
        <Button title="Dark Mode ( Coming Soon... )" type={ButtonType.Dark} />
        {children}
      </body>
    </html>
  );
}
