import axios from 'axios';
import { Inter } from 'next/font/google';
import Button, { ButtonType } from './components/atoms/Button';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  axios.defaults.baseURL = 'http://localhost:4000';

  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        ></link>
      </head>
      <body className="container">
        <div className="d-flex justify-content-between">
          <Button
            title="Dark Mode ( Coming Soon... )"
            buttonType={ButtonType.Dark}
          />
          <Link href="/">
            <Button title="Back to Home" buttonType={ButtonType.Info} />
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
